# Generated by Django 3.1.5 on 2022-05-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='desk',
            field=models.FloatField(max_length=264, null=True),
        ),
    ]
