# Generated by Django 3.1.5 on 2022-05-27 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0003_auto_20220527_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='favorit',
        ),
        migrations.CreateModel(
            name='Birouri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ManyToManyField(related_name='user2', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ManyToManyField(related_name='user3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
