# Generated by Django 3.1.5 on 2022-05-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20220528_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='birouri',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
