# Generated by Django 3.1.5 on 2022-05-27 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0005_birouri_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birouri',
            name='user',
        ),
        migrations.AddField(
            model_name='birouri',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='birouri',
            name='user2',
        ),
        migrations.AddField(
            model_name='birouri',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='birouri',
            name='user3',
        ),
        migrations.AddField(
            model_name='birouri',
            name='user3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user3', to=settings.AUTH_USER_MODEL),
        ),
    ]
