# Generated by Django 3.1.5 on 2022-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_desk_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='imagine',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
