# Generated by Django 3.1.5 on 2022-05-28 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0010_auto_20220528_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birouri',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='birouri',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='birouri',
            name='user',
        ),
        migrations.AddField(
            model_name='birouri',
            name='user',
            field=models.ManyToManyField(null=True, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
