# Generated by Django 3.1.5 on 2022-05-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20220528_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birouri',
        ),
    ]
