# Generated by Django 3.1.5 on 2022-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='tag',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
