# Generated by Django 3.1.5 on 2022-05-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_places_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesSofia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('desk', models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
