# Generated by Django 3.1.5 on 2022-05-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20220528_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlacesSofia',
            new_name='Places',
        ),
    ]
