# Generated by Django 3.1.5 on 2022-05-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_auto_20220528_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='user',
            new_name='favorit',
        ),
    ]
