# Generated by Django 3.1.5 on 2022-05-28 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0020_places_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='favorit',
            field=models.ManyToManyField(blank=True, related_name='favorit', to=settings.AUTH_USER_MODEL),
        ),
    ]
