# Generated by Django 3.1.5 on 2022-05-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_auto_20220528_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='user',
        ),
    ]
