# Generated by Django 3.1.5 on 2022-05-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_question_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
    ]
