# Generated by Django 3.1.5 on 2022-05-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_auto_20220528_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
