# Generated by Django 3.1.5 on 2022-05-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=264, null=True)),
                ('option2', models.CharField(max_length=264, null=True)),
                ('option3', models.CharField(max_length=264, null=True)),
                ('option4', models.CharField(max_length=264, null=True)),
            ],
        ),
    ]
