# Generated by Django 3.1.5 on 2022-05-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option1',
            field=models.CharField(choices=[('Da', 'Da'), ('Nu', 'Nu')], max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option2',
            field=models.CharField(choices=[('Da', 'Da'), ('Nu', 'Nu')], max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option3',
            field=models.CharField(choices=[('Da', 'Da'), ('Nu', 'Nu')], max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option4',
            field=models.CharField(choices=[('Da', 'Da'), ('Nu', 'Nu')], max_length=264, null=True),
        ),
    ]
