# Generated by Django 3.1.5 on 2022-05-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_auto_20220528_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='user',
        ),
    ]
